Steps for the international instance

diff --git a/.github/workflows/maven-publish.yml b/.github/workflows/maven-publish.yml
--- a/.github/workflows/maven-publish.yml
+++ b/.github/workflows/maven-publish.yml
@@ -16,6 +16,11 @@ env:
   CONTAINER_NAME_INTERNATIONAL: dhis_pss_international
   IMAGE_NAME_INTERNATIONAL: dnjau/dhis_pss_international:v1
 
+  SSH_PASS_1: Sc281-6736/2014
+  SSH_HOST_2: 172.104.91.99
+  CONTAINER_NAME_NATIONAL: dhis_pss_national
+  IMAGE_NAME_NATIONAL: dnjau/dhis_pss_national:v1
+
 #  SSH_KEY_2: ${{ secrets.SSH_KEY_2 }}
 #  SSH_HOST_2: 172.104.91.99
 #  SSH_USER_2: dnjau
@@ -77,3 +82,61 @@ jobs:
 
 
 
+
+  build_microservice_national:
+    runs-on: ubuntu-20.04
+
+    steps:
+      - name: Set up Java
+        uses: actions/setup-java@v3
+        with:
+          java-version: 11
+          distribution: temurin
+      - name: Checkout code
+        uses: actions/checkout@v2
+
+      - name: Build National Instance
+        run: |
+          cd NationalInstance
+          mvn clean install
+
+      - name: Build & push National Docker image
+        run: |
+          cd NationalInstance
+          docker buildx build -t ${{ env.IMAGE_NAME_NATIONAL }} .
+          docker login -u ${{ env.DOCKER_USERNAME }} -p ${{ env.DOCKER_PASSWORD }}
+          docker push ${{ env.IMAGE_NAME_NATIONAL }}
+          docker logout
+
+      - name: Build & push International Docker image
+        run: |
+          cd InternationalInstance
+          docker buildx build -t ${{ env.IMAGE_NAME_INTERNATIONAL }} .
+          docker login -u ${{ env.DOCKER_USERNAME }} -p ${{ env.DOCKER_PASSWORD }}
+          docker push ${{ env.IMAGE_NAME_INTERNATIONAL }}
+          docker logout
+
+      - name: Remote ssh to server and update National instance
+        uses: appleboy/ssh-action@master
+        with:
+          host: ${{ env.SSH_HOST_2 }}
+          username: ${{ env.SSH_USER }}
+          password: ${{ env.SSH_PASS }}
+          port: ${{ env.SSH_PORT }}
+          script_stop: true
+          script: |
+            if docker ps -a --format '{{.Names}}' | grep -q ${{ env.CONTAINER_NAME_NATIONAL }}; then
+              echo "Check 1"
+              docker stop ${{ env.CONTAINER_NAME_NATIONAL }}
+              docker rm ${{ env.CONTAINER_NAME_NATIONAL }}
+            fi
+            docker pull --quiet ${{ env.IMAGE_NAME_NATIONAL }}
+            if [ $? -eq 0 ]; then
+              echo "Docker image ${{ env.IMAGE_NAME_NATIONAL }} pulled successfully"
+            else
+              echo "Error: Failed to pull Docker image ${{ env.IMAGE_NAME_NATIONAL }}"
+              exit 1
+            fi
+            docker run -d --name ${{ env.CONTAINER_NAME_NATIONAL }} -p 7007:7007 ${{ env.IMAGE_NAME_NATIONAL }}
+            docker logout
+            sleep 10
