Added file service

diff --git a/.github/workflows/maven-publish.yml b/.github/workflows/maven-publish.yml
--- a/.github/workflows/maven-publish.yml
+++ b/.github/workflows/maven-publish.yml
@@ -26,6 +26,10 @@ env:
   CONTAINER_NAME_NATIONAL: dhis_pss_national
   IMAGE_NAME_NATIONAL: dnjau/dhis_pss_national:v1
 
+# FILE STORAGE
+  CONTAINER_NAME_FILE: dhis_pss_file
+  IMAGE_NAME_FILE: dnjau/dhis_pss_file:v1
+
 
 jobs:
   build_microservice_international:
@@ -138,5 +142,60 @@ jobs:
               exit 1
             fi
             docker run -d --name ${{ env.CONTAINER_NAME_NATIONAL }} -p 7001:7001 ${{ env.IMAGE_NAME_NATIONAL }}
+            docker logout
+            sleep 10
+
+  build_microservice_file:
+    runs-on: ubuntu-20.04
+
+    steps:
+      - name: Set up Java
+        uses: actions/setup-java@v3
+        with:
+          java-version: 11
+          distribution: temurin
+      - name: Checkout code
+        uses: actions/checkout@v2
+
+      - name: Build File Service
+        run: |
+          cd FileService
+          mvn clean install
+
+      - name: Build & push File Service Docker image
+        run: |
+          cd FileService
+          docker build -t ${{ env.IMAGE_NAME_FILE }} .
+          docker login -u ${{ env.DOCKER_USERNAME }} -p ${{ env.DOCKER_PASSWORD }}
+          docker push ${{ env.IMAGE_NAME_FILE }}
+          docker logout
+
+      - name: Setup SSH keys
+        uses: webfactory/ssh-agent@v0.5.0
+        with:
+          ssh-private-key: ${{ env.SSH_PASS_NATIONAL }}
+
+      - name: Remote ssh to server and update File Service
+        uses: appleboy/ssh-action@master
+        with:
+          host: ${{ env.SSH_HOST_NATIONAL }}
+          username: ${{ env.SSH_USER_NATIONAL }}
+          port: ${{ env.SSH_PORT }}
+          key: ${{ env.SSH_PASS_NATIONAL }}
+          script_stop: true
+          script: |
+            if docker ps -a --format '{{.Names}}' | grep -q ${{ env.CONTAINER_NAME_FILE }}; then
+              echo "Check 1"
+              docker stop ${{ env.CONTAINER_NAME_FILE }}
+              docker rm ${{ env.CONTAINER_NAME_FILE }}
+            fi
+            docker pull --quiet ${{ env.IMAGE_NAME_FILE }}
+            if [ $? -eq 0 ]; then
+              echo "Docker image ${{ env.IMAGE_NAME_FILE }} pulled successfully"
+            else
+              echo "Error: Failed to pull Docker image ${{ env.IMAGE_NAME_FILE }}"
+              exit 1
+            fi
+            docker run -d --name ${{ env.CONTAINER_NAME_FILE }} -p 7003:7003 ${{ env.IMAGE_NAME_FILE }}
             docker logout
             sleep 10
