Added email service to workflow

diff --git a/.github/workflows/maven-publish.yml b/.github/workflows/maven-publish.yml
--- a/.github/workflows/maven-publish.yml
+++ b/.github/workflows/maven-publish.yml
@@ -30,6 +30,10 @@ env:
   CONTAINER_NAME_FILE: dhis_pss_file
   IMAGE_NAME_FILE: dnjau/dhis_pss_file:v1
 
+# EMAIL SERVICE
+  CONTAINER_NAME_MAIL: dhis_pss_mail
+  IMAGE_NAME_MAIL: dnjau/dhis_pss_mail:v1
+
 
 jobs:
   build_microservice_international:
@@ -197,5 +201,59 @@ jobs:
               exit 1
             fi
             docker run -d --name ${{ env.CONTAINER_NAME_FILE }} -p 7003:7003 ${{ env.IMAGE_NAME_FILE }}
+            docker logout
+            sleep 10
+  build_microservice_email_service:
+    runs-on: ubuntu-20.04
+
+    steps:
+      - name: Set up Java
+        uses: actions/setup-java@v3
+        with:
+          java-version: 11
+          distribution: temurin
+      - name: Checkout code
+        uses: actions/checkout@v2
+
+      - name: Build Email Service
+        run: |
+          cd MailServer
+          mvn clean install
+
+      - name: Build & push Email Service Docker image
+        run: |
+          cd MailServer
+          docker build -t ${{ env.IMAGE_NAME_MAIL }} .
+          docker login -u ${{ env.DOCKER_USERNAME }} -p ${{ env.DOCKER_PASSWORD }}
+          docker push ${{ env.IMAGE_NAME_MAIL }}
+          docker logout
+
+      - name: Setup SSH keys
+        uses: webfactory/ssh-agent@v0.5.0
+        with:
+          ssh-private-key: ${{ env.SSH_PASS_NATIONAL }}
+
+      - name: Remote ssh to server and update File Service
+        uses: appleboy/ssh-action@master
+        with:
+          host: ${{ env.SSH_HOST_NATIONAL }}
+          username: ${{ env.SSH_USER_NATIONAL }}
+          port: ${{ env.SSH_PORT }}
+          key: ${{ env.SSH_PASS_NATIONAL }}
+          script_stop: true
+          script: |
+            if docker ps -a --format '{{.Names}}' | grep -q ${{ env.CONTAINER_NAME_MAIL }}; then
+              echo "Check 1"
+              docker stop ${{ env.CONTAINER_NAME_MAIL }}
+              docker rm ${{ env.CONTAINER_NAME_MAIL }}
+            fi
+            docker pull --quiet ${{ env.IMAGE_NAME_MAIL }}
+            if [ $? -eq 0 ]; then
+              echo "Docker image ${{ env.IMAGE_NAME_MAIL }} pulled successfully"
+            else
+              echo "Error: Failed to pull Docker image ${{ env.IMAGE_NAME_MAIL }}"
+              exit 1
+            fi
+            docker run -d --name ${{ env.CONTAINER_NAME_MAIL }} -p 7007:7007 ${{ env.IMAGE_NAME_MAIL }}
             docker logout
             sleep 10
