feat(core): Check if the docker pull command is complete

diff --git a/.github/workflows/maven-publish.yml b/.github/workflows/maven-publish.yml
--- a/.github/workflows/maven-publish.yml
+++ b/.github/workflows/maven-publish.yml
@@ -52,18 +52,25 @@ jobs:
     needs: build_microservice_international
 
     steps:
-    - name: SSH into server and update container
-      run: |
-        sshpass -p ${{ env.SSH_PASS }} ssh -o StrictHostKeyChecking=no -l ${{ env.SSH_USER }} ${{ env.SSH_HOST_1 }}
-        if docker ps -a --format '{{.Names}}' | grep -q ${{ env.CONTAINER_NAME_INTERNATIONAL }}; then
-          docker stop ${{ env.CONTAINER_NAME_INTERNATIONAL }}
-          docker rm ${{ env.CONTAINER_NAME_INTERNATIONAL }}
-        fi
-        docker pull ${{ env.IMAGE_NAME_INTERNATIONAL }}
-        docker run -d --name ${{ env.CONTAINER_NAME_INTERNATIONAL }} -p 7007:7007 ${{ env.IMAGE_NAME_INTERNATIONAL }}
-        while [ "$(docker inspect -f '{{.State.Running}}' ${{ env.CONTAINER_NAME_INTERNATIONAL }})" != "true" ]; do
-          sleep 10;
-        done;
-        docker logout
-        exit
+      - name: SSH into server and update container
+        run: |
+          sshpass -p ${{ env.SSH_PASS }} ssh -o StrictHostKeyChecking=no -l ${{ env.SSH_USER }} ${{ env.SSH_HOST_1 }}
+          if docker ps -a --format '{{.Names}}' | grep -q ${{ env.CONTAINER_NAME_INTERNATIONAL }}; then
+            docker stop ${{ env.CONTAINER_NAME_INTERNATIONAL }}
+            docker rm ${{ env.CONTAINER_NAME_INTERNATIONAL }}
+          fi
+          docker pull --quiet ${{ env.IMAGE_NAME_INTERNATIONAL }}
+          if [ $? -eq 0 ]; then
+            echo "Docker image ${env.IMAGE_NAME_INTERNATIONAL} pulled successfully"
+          else
+            echo "Error: Failed to pull Docker image ${env.IMAGE_NAME_INTERNATIONAL}"
+            exit 1
+          fi
+          docker run -d --name ${{ env.CONTAINER_NAME_INTERNATIONAL }} -p 7007:7007 ${{ env.IMAGE_NAME_INTERNATIONAL }}
+          while [ "$(docker inspect -f '{{.State.Running}}' ${{ env.CONTAINER_NAME_INTERNATIONAL }})" != "true" ]; do
+            sleep 10;
+          done;
+          docker logout
+          exit
+
 
